language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - INSTALL_EXTRAS=[VISA,plotting]
  - INSTALL_EXTRAS=[VISA,plotting,Faster-fractions]

#use container based infrastructure
sudo: false

#these directories are persistent
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/miniconda3_pkgs
    - $HOME/Downloads

# Setup anaconda
before_install:
# install miniconda with symlink of pkg dir to cache
  - chmod +x ./install_miniconda3.sh
  - ./install_miniconda3.sh
#
  - export PATH=$HOME/miniconda3/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip
  - conda install -q -n test-environment gmpy2
  - source activate test-environment
  - pip install coverage coveralls
install:
  - pip install .$INSTALL_EXTRAS
script:
  - "coverage run --source=qupulse --rcfile=coverage.ini setup.py test"
after_success:
  - coveralls

notifications:
  email: false
