language: python
python:
  - 3.5
  - 3.6
env:
  - INSTALL_EXTRAS=[VISA,plotting]
  - INSTALL_EXTRAS=[VISA,plotting,Faster-fractions]

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: INSTALL_EXTRAS=[VISA,plotting]
    - python: 3.7
      dist: xenial
      sudo: true
      env: INSTALL_EXTRAS=[VISA,plotting,Faster-fractions]

#use container based infrastructure
sudo: false

#these directories are persistent
cache: pip

# install dependencies for gmpy2
addons:
  apt:
    update: true
    packages:
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev

before_install:
  - pip install coverage coveralls

  # for tektronix driver tests (todo: move to pip)
  - pip install https://github.com/qutech/TekAwg/archive/qc_toolkit_1.zip
install:
  - pip install .$INSTALL_EXTRAS
script:
  - "coverage run --source=qupulse --rcfile=coverage.ini setup.py test"
after_success:
  - coveralls

notifications:
  email: false
