language: generic

env:
  - CONDA_PYTHON_VERSION=3.5
  - CONDA_PYTHON_VERSION=3.6

#use container based infrastructure
sudo: false


# Setup anaconda
before_install:
# install miniconda with symlink of pkg dir to cache
  - chmod +x ./install_miniconda3.sh
  - ./install_miniconda3.sh
#
  - export PATH=$HOME/miniconda3/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$CONDA_PYTHON_VERSION pip atlas numpy
  - source activate test-environment
  - pip install pyflakes coverage coveralls matplotlib
install:
  - python setup.py install
script:
  - "coverage run --source=qctoolkit --rcfile=coverage.ini setup.py test"
after_success:
    - coveralls

notifications:
  email: false
